#! /bin/bash 

ele=$1
opts=$2
text="`wget -qO- \"https://physics.nist.gov/cgi-bin/XrayTrans/search.pl?download=tab&element=${ele}&trans=All&lower=&upper=&units=eV\"`"
if [ "${opts}" != "--dlg" ];then
	printf "\n"
	echo "${text}" | awk 'NR>4 {FS="\t"; \
					if ($1=="Ele.")
						printf "\033[1;34m%-10s %-10s %-10s %-10s %-10s %-10s\n",$1,$3,$4,$5,$6,$7;
					else if ($3=="K edge")
						printf "%-10s \033[1;32m%-10s %-10s %-10s %-10s %-10s\n",$1,$3,$4,$5,$6,$7;
					else if ($3=="L1 edge")
						printf "%-10s \033[1;32m%-10s %-10s %-10s %-10s %-10s\n",$1,$3,$4,$5,$6,$7;
					else if ($3=="L2 edge")
						printf "%-10s \033[1;32m%-10s %-10s %-10s %-10s %-10s\n",$1,$3,$4,$5,$6,$7;
					else if ($3=="L3 edge")
						printf "%-10s \033[1;32m%-10s %-10s %-10s %-10s %-10s\n",$1,$3,$4,$5,$6,$7;
					else
						printf "\033[0m%-10s %-10s %-10s %-10s %-10s %-10s\n",$1,$3,$4,$5,$6,$7;
					}' 
	printf "\n"
fi
if [ "${opts}" == "--dlg" ];then
	lines=$(( $(tput lines)/2 ))
	cols=$(( 2*$(tput cols)/3 ))
	echo "${text}" | awk 'NR>4 {FS="\t";\
					 printf "%-10s %-10s %-10s %-10s %-10s %-10s\n",$1,$3,$4,$5,$6,$7;\
					}' > xedge_wget_result.txt.tmp 
	dialog --title "| Xedge >>> $ele |" --textbox xedge_wget_result.txt.tmp $lines $cols
	rm xedge_wget_result.txt.tmp
fi
	
